POST http://localhost:8080/student
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"studentUsername": "Olia5", "password": "helloworld2", "grade" : 1, "deadlinesId": null }

###

POST http://localhost:8080/deadline
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "taskDescription": "4 d u",
  "deadlineDate": "26.11.2020",
  "maxPoints": 5,
  "isDone": false,
  "studentsId" : [2],
  "subjectId" : 11
}

###

DELETE http://localhost:8080/subject/14
//Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

PUT http://localhost:8080/subject/15
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"subjectCode": "BI-PJV", "numberOfCredits": 4}

###

GET http://localhost:8080/student/all/9
Cache-Control: no-cache
Content-Type: application/json

