GET http://localhost:8080/deadline/10
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:8080/deadline/all
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/deadline/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "taskDescription": "1 d u",
  "deadlineDate": "26.12.2020",
  "maxPoints": 6,
  "studentsId" : [1,2],
  "subjectId" : 6
}

###

PUT http://localhost:8080/deadline/update/26
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "taskDescription": "8 d u",
  "deadlineDate": "26.11.2020",
  "maxPoints": 10,
  "studentsId" : [2,25],
  "subjectId" : 11
}

###

DELETE http://localhost:8080/deadline/delete/26
Cache-Control: no-cache
Content-Type: application/json

