GET http://localhost:8080/subject/13
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:8080/subject/all?page=0&size=3
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/subject
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "subjectCode": "BI-XZZ",
  "numberOfCredits": 4
}

###

PUT http://localhost:8080/subject/update/29
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "subjectCode": "BI-AG2",
  "numberOfCredits": 5
}

###

DELETE http://localhost:8080/subject/delete/29
Cache-Control: no-cache
Content-Type: application/json

